export const LOGIN = 'USER/LOGIN'
export const LOGOUT = 'USER/LOGOUT'
export const LOGIN_SUCCESS = "LOGIN/SUCESS";
export const LOGIN_FAILED = "LOGIN/FAILED";
export const LIST_FRIENDS = "SOCKET/FRIENDS";
export const GET_LIST_FRIENDS = "SOCKET/GET/FRIENDS";
export const CONNECT_SOCKET = "SOCKET/CONNECT";
export const CONNECT_SOCKET_SUCESS = "SOCKET/CONNECT/SUCCESS";
